<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 15px; height: 80px">

# Project 1

### Building "Pokemon Stay"

---
You are an analyst at a "scrappy" online gaming company that specializes in remakes of last year's fads.

Your boss, who runs the product development team, is convinced that Pokemon Go's fatal flaw was that you had to actually move around outside. She has design mock-ups for a new game called Pokemon Stay: in this version players still need to move, but just from website to website. Pokemon gyms are now popular online destinations, and catching Pokemon in the "wild" simply requires browsing the internet for hours in the comfort of your home.

She wants you to program a prototype version of the game and analyze the planned content to help the team calibrate the design.

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Building-&quot;Pokemon-Stay&quot;" data-toc-modified-id="Building-&quot;Pokemon-Stay&quot;-0.1">Building "Pokemon Stay"</a></span><ul class="toc-item"><li><span><a href="#Package-imports" data-toc-modified-id="Package-imports-0.1.1">Package imports</a></span></li></ul></li></ul></li><li><span><a href="#1.-Defining-a-player" data-toc-modified-id="1.-Defining-a-player-1">1. Defining a player</a></span></li><li><span><a href="#2.-Defining-&quot;gym&quot;-locations" data-toc-modified-id="2.-Defining-&quot;gym&quot;-locations-2">2. Defining "gym" locations</a></span></li><li><span><a href="#3.-Create-a-pokedex" data-toc-modified-id="3.-Create-a-pokedex-3">3. Create a pokedex</a></span></li><li><span><a href="#4.-Create-a-data-structure-for-players" data-toc-modified-id="4.-Create-a-data-structure-for-players-4">4. Create a data structure for players</a></span><ul class="toc-item"><li><span><a href="#4.1" data-toc-modified-id="4.1-4.1">4.1</a></span></li><li><span><a href="#4.2" data-toc-modified-id="4.2-4.2">4.2</a></span></li></ul></li><li><span><a href="#5.-Add-captured-pokemon-for-each-player" data-toc-modified-id="5.-Add-captured-pokemon-for-each-player-5">5. Add captured pokemon for each player</a></span></li><li><span><a href="#6.-What-gyms-have-players-visited?" data-toc-modified-id="6.-What-gyms-have-players-visited?-6">6. What gyms have players visited?</a></span><ul class="toc-item"><li><span><a href="#6.1" data-toc-modified-id="6.1-6.1">6.1</a></span></li><li><span><a href="#6.2" data-toc-modified-id="6.2-6.2">6.2</a></span></li></ul></li><li><span><a href="#7.-Calculate-player-&quot;power&quot;." data-toc-modified-id="7.-Calculate-player-&quot;power&quot;.-7">7. Calculate player "power".</a></span></li><li><span><a href="#8.-Load-a-pokedex-file-containing-all-the-pokemon" data-toc-modified-id="8.-Load-a-pokedex-file-containing-all-the-pokemon-8">8. Load a pokedex file containing all the pokemon</a></span><ul class="toc-item"><li><span><a href="#8.1" data-toc-modified-id="8.1-8.1">8.1</a></span></li><li><span><a href="#8.2-Parse-the-raw-pokedex-with-list-comprehensions" data-toc-modified-id="8.2-Parse-the-raw-pokedex-with-list-comprehensions-8.2">8.2 Parse the raw pokedex with list comprehensions</a></span></li></ul></li><li><span><a href="#9.-Write-a-function-to-generate-the-full-pokedex" data-toc-modified-id="9.-Write-a-function-to-generate-the-full-pokedex-9">9. Write a function to generate the full pokedex</a></span></li><li><span><a href="#10.-Write-a-function-to-generate-a-&quot;filtered&quot;-pokedex" data-toc-modified-id="10.-Write-a-function-to-generate-a-&quot;filtered&quot;-pokedex-10">10. Write a function to generate a "filtered" pokedex</a></span></li><li><span><a href="#11.-Descriptive-statistics-on-the-prototype-pokedex" data-toc-modified-id="11.-Descriptive-statistics-on-the-prototype-pokedex-11">11. Descriptive statistics on the prototype pokedex</a></span><ul class="toc-item"><li><span><a href="#11.1" data-toc-modified-id="11.1-11.1">11.1</a></span></li><li><span><a href="#11.2" data-toc-modified-id="11.2-11.2">11.2</a></span></li></ul></li><li><span><a href="#12.-Calibrate-the-frequency-of-Pokemon" data-toc-modified-id="12.-Calibrate-the-frequency-of-Pokemon-12">12. Calibrate the frequency of Pokemon</a></span></li></ul></div>

#### Package imports

The pprint package below is the only package imported here, and it's not even strictly required to do any of the project. Printing python variables and objects with pprint can help to format them in a "prettier" way.

In [1]:
from pprint import pprint

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 1. Defining a player

---

The player variables are:

    player_id : id code unique to each player (integer)
    player_name : entered name of the player (string)
    time_played : number of times played the game in minutes (float)
    player_pokemon: the player's captured pokemon (dictionary)
    gyms_visited: ids of the gyms that a player has visited (list)
    
Create the components for a player object by defining each of these variables. The dictionary and list variables should just be defined as empty; you can use any (correctly typed) values for the others.

In [2]:
player_id = 1
player_name = 'Bob Marley'
time_played = 300.5
player_pokemon = {}
gyms_visited = []

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 2. Defining "gym" locations

---

As the sole programmer, Pokemon Stay will have to start small. To begin, there will be 10 different gym location websites on the internet. The gym locations are:

    1. 'reddit.com'
    2. 'amazon.com'
    3. 'twitter.com'
    4. 'linkedin.com'
    5. 'ebay.com'
    6. 'netflix.com'
    7. 'sporcle.com'
    8. 'stackoverflow.com'
    9. 'github.com'
    10. 'quora.com'

1. Set up a list of all the gym locations. This will be a list of strings.
2. Append two of these locations to your player's list of visited gyms.
3. Print the list.

In [3]:
gym_locations = ['reddit.com','amazon.com','twitter.com','linkedin.com','ebay.com','netflix.com','sporcle.com','stackoverflow.com','github.com','quora.com']

In [4]:
gyms_visited.extend(gym_locations[2:4])

In [5]:
pprint(gyms_visited)

['twitter.com', 'linkedin.com']


<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 3. Create a pokedex

---

We also need to create some pokemon to catch. Each pokemon will be defined by these variables:

    pokemon_id : unique identifier for each pokemon (integer)
    name : the name of the pokemon (string)
    type : the category of pokemon (string)
    hp : base hitpoints (integer)
    attack : base attack (integer)
    defense : base defense (integer)
    special_attack : base special attack (integer)
    special_defense : base sepecial defense (integer)
    speed : base speed (integer)

We are only going to create 3 different pokemon with these `pokemon_id` and `pokemon_name` values:

    1 : 'charmander'
    2 : 'squirtle'
    3 : 'bulbasaur'

Create a dictionary that will contain the pokemon. The keys of the dictionary will be the `pokemon_id` and the values will themselves be dictionaries that contain the other pokemon variables. The structure of the pokedex dictionary will start like so:
     
     {
         1: {
                 'name':'charmander',
                 'type':'fire',
                 ...
                 
The `type` of charmander, squirtle, and bulbasaur should be `'fire'`, `'water'`, and `'poison'` respectively. The other values are up to you, make them anything you like!

Print (or pretty print) the pokedex dictionary with the 3 pokemon.

In [6]:
POKEDEX = {
    1: {
        'name':'charmander',
        'type':'fire',
        'hp' : '20',
        'attack' : '5',
        'defense' : '3',
        'special_attack' : '15',
        'special_defense' : '10',
        'speed' : '8'
        },
    
    2:  {
        'name': 'squirtle',
        'type': 'water',
        'hp' : '15',
        'attack' : '2',
        'defense' : '6',
        'special_attack' : '23',
        'special_defense' : '10',
        'speed' : '2'
        },
    
    3:  {
        'name':'bulbasaur',
        'type':'poison',
        'hp' : '30',
        'attack' : '19',
        'defense' : '20',
        'special_attack' : '33',
        'special_defense' : '20',
        'speed' : '22'
        
        }
    
         }

pprint(POKEDEX)
#pprint prints alphabetically

{1: {'attack': '5',
     'defense': '3',
     'hp': '20',
     'name': 'charmander',
     'special_attack': '15',
     'special_defense': '10',
     'speed': '8',
     'type': 'fire'},
 2: {'attack': '2',
     'defense': '6',
     'hp': '15',
     'name': 'squirtle',
     'special_attack': '23',
     'special_defense': '10',
     'speed': '2',
     'type': 'water'},
 3: {'attack': '19',
     'defense': '20',
     'hp': '30',
     'name': 'bulbasaur',
     'special_attack': '33',
     'special_defense': '20',
     'speed': '22',
     'type': 'poison'}}


<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 4. Create a data structure for players

---

### 4.1 

In order to maintain a database of multiple players, create a dictionary that keeps track of players indexed by `player_id`. 

The keys of the dictionary will be `player_id` and the values will be dictionaries containing each player's variables (from question 1). 

Construct the `players` dictionary and insert the player that you defined in question 1, then print `players`.

In [7]:
player_id = 1
player_name = 'Bob Marley'
time_played = 300.5
player_pokemon = {}
gyms_visited = []

In [8]:
PLAYERS = {
player_id: {
            'player_name':'Bob Marley',
            'time_played': 300.5,
            'player_pokemon': {},
            'gyms_visited': ['twitter.com', 'linkedin.com']
            }
           }
             
           

pprint(PLAYERS)

{1: {'gyms_visited': ['twitter.com', 'linkedin.com'],
     'player_name': 'Bob Marley',
     'player_pokemon': {},
     'time_played': 300.5}}


---

### 4.2

Create a new player with `player_id = 2` in the `players` dictionary. Leave the `'player_pokemon'` dictionary empty. Append `'stackoverflow'` and `'github.com'` to the `'gyms_visited'` list for player 2.

The `'player_name'` and `'time_played'` values are up to you, but must be a string and float, respectively.

Remember, the player_id is the key for the player in the players dictionary.

Print the `players` dictionary with the new player inserted.

In [9]:
player_2 = {'player_name':'Guy Ritchie','time_played': 875.5,'player_pokemon': {},'gyms_visited': []}

In [10]:
player_2['gyms_visited'] += ['stackoverflow.com','github.com']
pprint(player_2)

{'gyms_visited': ['stackoverflow.com', 'github.com'],
 'player_name': 'Guy Ritchie',
 'player_pokemon': {},
 'time_played': 875.5}


In [11]:
PLAYERS[2] = player_2
pprint(PLAYERS)


{1: {'gyms_visited': ['twitter.com', 'linkedin.com'],
     'player_name': 'Bob Marley',
     'player_pokemon': {},
     'time_played': 300.5},
 2: {'gyms_visited': ['stackoverflow.com', 'github.com'],
     'player_name': 'Guy Ritchie',
     'player_pokemon': {},
     'time_played': 875.5}}


<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 5. Add captured pokemon for each player

---

The `'player_pokemon'` keyed dictionaries for each player keep track of which of the pokemon each player has.

The keys of the `'player_pokemon'` dictionaries are the pokemon ids that correspond to the ids in the `pokedex` dictionary you created earlier. The values are integers specifying the stats for the pokemon.

Give player 1 a squirtle. Give player 2 a charmander and a bulbasaur.

Print the players dictionary after adding the pokemon for each player.


In [12]:
# for each entry in PLAYERS dictionary, find key 'player_pokemon' and add entry from pokedex dictionary 
PLAYERS[1]['player_pokemon'] = {1: POKEDEX[2]}
PLAYERS[2]['player_pokemon'] = {1: POKEDEX[1], 2: POKEDEX[3]}

pprint(PLAYERS)

{1: {'gyms_visited': ['twitter.com', 'linkedin.com'],
     'player_name': 'Bob Marley',
     'player_pokemon': {1: {'attack': '2',
                            'defense': '6',
                            'hp': '15',
                            'name': 'squirtle',
                            'special_attack': '23',
                            'special_defense': '10',
                            'speed': '2',
                            'type': 'water'}},
     'time_played': 300.5},
 2: {'gyms_visited': ['stackoverflow.com', 'github.com'],
     'player_name': 'Guy Ritchie',
     'player_pokemon': {1: {'attack': '5',
                            'defense': '3',
                            'hp': '20',
                            'name': 'charmander',
                            'special_attack': '15',
                            'special_defense': '10',
                            'speed': '8',
                            'type': 'fire'},
                        2: {'attack': '19',
         

## 6. What gyms have players visited?

---

# <img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

### 6.1

Write a for-loop that:

1. Iterates through the `pokemon_gyms` list of gym locations you defined before.
2. For each gym, iterate through each player in the `players` dictionary with a second, internal for-loop.
3. If the player has visited the gym, print out "[player] has visited [gym location].", filling in [player] and [gym location] with the current player's name and current gym location.

In [13]:
#iterates through the pokemon_gyms 
for gym in gym_locations:
    
        # loops through gyms
            for i in PLAYERS:
                
                # loops through players dictionary
                    for j in range(len(PLAYERS[i]['gyms_visited'])):
                        
                        #checks if gym location is in each players dictionary entry
                            if PLAYERS[i]['gyms_visited'][j] == gym:
                                
                                #prints result
                                print(PLAYERS[i]['player_name'], "has visited",gym)
                              

Bob Marley has visited twitter.com
Bob Marley has visited linkedin.com
Guy Ritchie has visited stackoverflow.com
Guy Ritchie has visited github.com


<img src="http://imgur.com/xDpSobf.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

### 6.2

How many times did that loop run? If you have N gyms and also N players, how many times would it run as a function of N?

Can you think of a more efficient way to accomplish the same thing? 

(You can write your answer as Markdown text.)

• How many times did that loop run?

I wanted to use %timeit to get the no. of times the loop ran but I could only see how to make this work in a function. Instead I used the below counters in the loop to give 40. Thats 10 x 2 x 2.


In [14]:
count_gyms = 0
count_players = 0
count_visits = 0


for gym in gym_locations:
    count_gyms += 1
    print('This is count no {} for gyms'.format(count_gyms))  

This is count no 1 for gyms
This is count no 2 for gyms
This is count no 3 for gyms
This is count no 4 for gyms
This is count no 5 for gyms
This is count no 6 for gyms
This is count no 7 for gyms
This is count no 8 for gyms
This is count no 9 for gyms
This is count no 10 for gyms


In [15]:
for i in PLAYERS:
    count_players += 1
    print('This is count no {} for players'.format(count_players))     

This is count no 1 for players
This is count no 2 for players


In [16]:
for j in range(len(PLAYERS[i]['gyms_visited'])):
    count_visits += 1
    print('This is count no {} for visits'.format(count_visits))
            

This is count no 1 for visits
This is count no 2 for visits


• If you have N gyms and also N players, how many times would it run as a function of N?

It would equate to N(gyms) * N(players) * N in N(gyms in players)

Can you think of a more efficient way to accomplish the same thing?

A nested list comprehension.

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 7. Calculate player "power".

---

Define a function that will calculate a player's "power". Player power is defined as the sum of the base statistics of all their pokemon.

Your function will:

1. Accept the `players` dictionary, `pokedex` dictionary, and a player_id as arguments.
2. For the specified player_id, look up that player's pokemon and their level(s).
3. Find and aggregate the attack and defense values for each of the player's pokemon from the `pokedex` dictionary.
4. Print "[player name]'s power is [player power].", where the player power is the sum of the base statistics for all of their pokemon.
5. Return the player's power value.

Print out the pokemon power for each of your players.

In [17]:
def player_power(PLAYERS, POKEDEX, player_id):
    
# place player pokemon into variable to make it easier to iterate through
    pokemon_in_player = PLAYERS[player_id]['player_pokemon']
    player_pow = 0
    
# loop through each pokemon held by each player and add defense / attack values
# in order to allow for addition I turned the values to integers
# print players name and total of powers from previous addition
    for pokemon in range(len(pokemon_in_player)):
        player_pow = int(pokemon_in_player[player_id]['attack'])+int(pokemon_in_player[player_id]['defense'])+int(pokemon_in_player[player_id]['special_attack'])+int(pokemon_in_player[player_id]['special_defense'])
        print(PLAYERS[player_id]['player_name'], "'s power is", player_pow)
        return player_pow
    
player_power(PLAYERS, POKEDEX, 1)
player_power(PLAYERS, POKEDEX, 2)

Bob Marley 's power is 41
Guy Ritchie 's power is 92


92

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 8. Load a pokedex file containing all the pokemon

---

### 8.1

While you were putting together the prototype code, your colleagues were preparing a dataset of Pokemon and their attributes. (This was a rush job, so they may have picked some crazy values for some...)

The code below loads information from a comma separated value (csv) file. You need to parse this string into a more useable format. The format of the string is:

- Rows are separated by newline characters: \n
- Columns are separated by commas: ,
- All cells in the csv are double quoted. Ex: "PokedexNumber" is the first cell of the first row.


Using for-loops, create a list of lists where each list within the overall list is a row of the csv/matrix, and each element in that list is a cell in that row. Additional criteria:

1. Quotes are removed from each cell item.
2. Numeric column values are converted to floats.
3. There are some cells that are empty and have no information. For these cells put a -1 value in place.

Your end result is effectively a matrix. Each list in the outer list is a row, and the *j*th elements of the list together form the *j*th column, which represents a data attribute. The first three lists in your pokedex list should look like this:

    ['PokedexNumber', 'Name', 'Type', 'Total', 'HP', 'Attack', 'Defense', 'SpecialAttack', 'SpecialDefense', 'Speed']
    [1.0, 'Bulbasaur', 'GrassPoison', 318.0, 45.0, 49.0, 49.0, 65.0, 65.0, 45.0]
    [2.0, 'Ivysaur', 'GrassPoison', 405.0, 60.0, 62.0, 63.0, 80.0, 80.0, 60.0]

In [73]:
# imported pandas library to allow pd.read
import pandas as pd

# Code to read in pokedex info
raw_pd = ''
pokedex_file = '/Users/KStamp/Desktop/GA/resource-datasets/pokemon/pokedex_basic.csv'
with open(pokedex_file, 'r') as f:
#     raw_pd = f.read()

#created a new variable to allow pandas to read file more clearly
      data = pd.read_csv(pokedex_file)
data

PokedexNumber                   Name          Type  Total  HP  Attack  \
0                1              Bulbasaur   GrassPoison    318  45      49   
1                2                Ivysaur   GrassPoison    405  60      62   
2                3               Venusaur   GrassPoison    525  80      82   
3                3  VenusaurMega Venusaur   GrassPoison    625  80     100   
4                4             Charmander          Fire    309  39      52   
..             ...                    ...           ...    ...  ..     ...   
795            719                Diancie     RockFairy    600  50     100   
796            719    DiancieMega Diancie     RockFairy    700  50     160   
797            720    HoopaHoopa Confined  PsychicGhost    600  80     110   
798            720     HoopaHoopa Unbound   PsychicDark    680  80     160   
799            721              Volcanion     FireWater    600  80     110   

     Defense  SpecialAttack  SpecialDefense  Speed  
0         49             65              65     45  
1         63             80              80     60  
2         83            100             100     80  
3        123            122             120     80  
4         43             60              50     65  
..       ...            ...             ...    ...  
795      150            100             150     50  
796      110            160             110    110  
797       60            150             130     70  
798       60            170             130     80  
799      120            130              90     70  

[800 rows x 10 columns]

In [19]:
# Code to read in pokedex info
raw_pd = ''
pokedex_file = '/Users/KStamp/Desktop/GA/resource-datasets/pokemon/pokedex_basic.csv'
with open(pokedex_file, 'r') as f:
    raw_pd = f.read()

# raw_pd

# The pokedex string is assigned to the raw_pd variable

In [20]:
# I changed data into a more read-able list by replacing the " " and removing the ''\n' using .split

pd_no_quotes = raw_pd.replace('"', '')
pd_split = pd_no_quotes.split('\n')


In [21]:
clean = []

# for each line in the data above, split on the ',' to create a new line and append to a new list
for a in range(len(pd_split)):
    pd_split2 = pd_split[a].split(",")
    clean.append(pd_split2)
    
# iterate through the new lines in the new list
# try changing the item to a float (meaning it is a number)
# if not then keep as is (for the letters)
    for l in range(len(clean)) :
        for i in range(len(clean[l])) :
            try :
                clean[l][i] = float(clean[l][i])
            except :
                    clean[l][i] = clean[l][i]

In [22]:
pprint(clean)

[['PokedexNumber',
  'Name',
  'Type',
  'Total',
  'HP',
  'Attack',
  'Defense',
  'SpecialAttack',
  'SpecialDefense',
  'Speed'],
 [1.0, 'Bulbasaur', 'GrassPoison', 318.0, 45.0, 49.0, 49.0, 65.0, 65.0, 45.0],
 [2.0, 'Ivysaur', 'GrassPoison', 405.0, 60.0, 62.0, 63.0, 80.0, 80.0, 60.0],
 [3.0, 'Venusaur', 'GrassPoison', 525.0, 80.0, 82.0, 83.0, 100.0, 100.0, 80.0],
 [3.0,
  'VenusaurMega Venusaur',
  'GrassPoison',
  625.0,
  80.0,
  100.0,
  123.0,
  122.0,
  120.0,
  80.0],
 [4.0, 'Charmander', 'Fire', 309.0, 39.0, 52.0, 43.0, 60.0, 50.0, 65.0],
 [5.0, 'Charmeleon', 'Fire', 405.0, 58.0, 64.0, 58.0, 80.0, 65.0, 80.0],
 [6.0, 'Charizard', 'FireFlying', 534.0, 78.0, 84.0, 78.0, 109.0, 85.0, 100.0],
 [6.0,
  'CharizardMega Charizard X',
  'FireDragon',
  634.0,
  78.0,
  130.0,
  111.0,
  130.0,
  85.0,
  100.0],
 [6.0,
  'CharizardMega Charizard Y',
  'FireFlying',
  634.0,
  78.0,
  104.0,
  78.0,
  159.0,
  115.0,
  100.0],
 [7.0, 'Squirtle', 'Water', 314.0, 44.0, 48.0, 65.0, 50.0, 

 [604.0, 'Eelektross', 'Electric', 515.0, 85.0, 115.0, 80.0, 105.0, 80.0, 50.0],
 [605.0, 'Elgyem', 'Psychic', 335.0, 55.0, 55.0, 55.0, 85.0, 55.0, 30.0],
 [606.0, 'Beheeyem', 'Psychic', 485.0, 75.0, 75.0, 75.0, 125.0, 95.0, 40.0],
 [607.0, 'Litwick', 'GhostFire', 275.0, 50.0, 30.0, 55.0, 65.0, 55.0, 20.0],
 [608.0, 'Lampent', 'GhostFire', 370.0, 60.0, 40.0, 60.0, 95.0, 60.0, 55.0],
 [609.0, 'Chandelure', 'GhostFire', 520.0, 60.0, 55.0, 90.0, 145.0, 90.0, 80.0],
 [610.0, 'Axew', 'Dragon', 320.0, 46.0, 87.0, 60.0, 30.0, 40.0, 57.0],
 [611.0, 'Fraxure', 'Dragon', 410.0, 66.0, 117.0, 70.0, 40.0, 50.0, 67.0],
 [612.0, 'Haxorus', 'Dragon', 540.0, 76.0, 147.0, 90.0, 60.0, 70.0, 97.0],
 [613.0, 'Cubchoo', 'Ice', 305.0, 55.0, 70.0, 40.0, 60.0, 40.0, 40.0],
 [614.0, 'Beartic', 'Ice', 485.0, 95.0, 110.0, 80.0, 70.0, 80.0, 50.0],
 [615.0, 'Cryogonal', 'Ice', 485.0, 70.0, 50.0, 30.0, 95.0, 135.0, 105.0],
 [616.0, 'Shelmet', 'Bug', 305.0, 50.0, 40.0, 85.0, 40.0, 65.0, 25.0],
 [617.0, 'Accelgor', 'B

<img src="http://imgur.com/xDpSobf.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

### 8.2 Parse the raw pokedex with list comprehensions

---

Perform the same parsing as above, but **using only a single list comprehension** instead of for loops. You may have nested list comprehensions within the main list comprehension! The output should be exactly the same.

In [23]:
# Attempted

#[[try clean[l][i] = float(clean[l][i]) except clean[l][i]=clean[l][i]] for i in range(len(clean[l])) for l in range(len(clean))]

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 9. Write a function to generate the full pokedex

---

Write a function that recreates the pokedex you made before, but with the data read in from the full pokemon file. Create a unique key value for each entry in the pokemon dictionary.

Your function should:

1. Take the parsed pokedex information you created above as an argument.
2. Return a dictionary in the same format as your original pokedex you created before containing the information from the parsed full pokedex file.

To test the function, print out the pokemon with id = 100.

In [70]:
header = clean[0]
data = clean[1:]

def pokedex_func(dataset):
    poke_dic = {} 
# created an empty dictionary to enter the pokemon data into 
    for row in range(len(dataset)):  
# loops through all the pokemon, creating a dictionary that zips header and data each time
        pok_id = row
        pokestats = dict(zip(header, dataset[row])) 
        poke_dic[pok_id] = pokestats
    return poke_dic

# prints full set of data with headers
trial = pokedex_func(data)
pprint(trial)

{0: {'Attack': 49.0,
     'Defense': 49.0,
     'HP': 45.0,
     'Name': 'Bulbasaur',
     'PokedexNumber': 1.0,
     'SpecialAttack': 65.0,
     'SpecialDefense': 65.0,
     'Speed': 45.0,
     'Total': 318.0,
     'Type': 'GrassPoison'},
 1: {'Attack': 62.0,
     'Defense': 63.0,
     'HP': 60.0,
     'Name': 'Ivysaur',
     'PokedexNumber': 2.0,
     'SpecialAttack': 80.0,
     'SpecialDefense': 80.0,
     'Speed': 60.0,
     'Total': 405.0,
     'Type': 'GrassPoison'},
 2: {'Attack': 82.0,
     'Defense': 83.0,
     'HP': 80.0,
     'Name': 'Venusaur',
     'PokedexNumber': 3.0,
     'SpecialAttack': 100.0,
     'SpecialDefense': 100.0,
     'Speed': 80.0,
     'Total': 525.0,
     'Type': 'GrassPoison'},
 3: {'Attack': 100.0,
     'Defense': 123.0,
     'HP': 80.0,
     'Name': 'VenusaurMega Venusaur',
     'PokedexNumber': 3.0,
     'SpecialAttack': 122.0,
     'SpecialDefense': 120.0,
     'Speed': 80.0,
     'Total': 625.0,
     'Type': 'GrassPoison'},
 4: {'Attack': 52.0,
    

      'SpecialAttack': 120.0,
      'SpecialDefense': 70.0,
      'Speed': 70.0,
      'Total': 465.0,
      'Type': 'ElectricSteel'},
 90: {'Attack': 65.0,
      'Defense': 55.0,
      'HP': 52.0,
      'Name': "Farfetch'd",
      'PokedexNumber': 83.0,
      'SpecialAttack': 58.0,
      'SpecialDefense': 62.0,
      'Speed': 60.0,
      'Total': 352.0,
      'Type': 'NormalFlying'},
 91: {'Attack': 85.0,
      'Defense': 45.0,
      'HP': 35.0,
      'Name': 'Doduo',
      'PokedexNumber': 84.0,
      'SpecialAttack': 35.0,
      'SpecialDefense': 35.0,
      'Speed': 75.0,
      'Total': 310.0,
      'Type': 'NormalFlying'},
 92: {'Attack': 110.0,
      'Defense': 70.0,
      'HP': 60.0,
      'Name': 'Dodrio',
      'PokedexNumber': 85.0,
      'SpecialAttack': 60.0,
      'SpecialDefense': 60.0,
      'Speed': 100.0,
      'Total': 460.0,
      'Type': 'NormalFlying'},
 93: {'Attack': 45.0,
      'Defense': 55.0,
      'HP': 65.0,
      'Name': 'Seel',
      'PokedexNumber': 86.0,

       'Speed': 100.0,
       'Total': 580.0,
       'Type': 'ElectricFlying'},
 158: {'Attack': 100.0,
       'Defense': 90.0,
       'HP': 90.0,
       'Name': 'Moltres',
       'PokedexNumber': 146.0,
       'SpecialAttack': 125.0,
       'SpecialDefense': 85.0,
       'Speed': 90.0,
       'Total': 580.0,
       'Type': 'FireFlying'},
 159: {'Attack': 64.0,
       'Defense': 45.0,
       'HP': 41.0,
       'Name': 'Dratini',
       'PokedexNumber': 147.0,
       'SpecialAttack': 50.0,
       'SpecialDefense': 50.0,
       'Speed': 50.0,
       'Total': 300.0,
       'Type': 'Dragon'},
 160: {'Attack': 84.0,
       'Defense': 65.0,
       'HP': 61.0,
       'Name': 'Dragonair',
       'PokedexNumber': 148.0,
       'SpecialAttack': 70.0,
       'SpecialDefense': 70.0,
       'Speed': 70.0,
       'Total': 420.0,
       'Type': 'Dragon'},
 161: {'Attack': 134.0,
       'Defense': 95.0,
       'HP': 91.0,
       'Name': 'Dragonite',
       'PokedexNumber': 149.0,
       'SpecialAttack

       'SpecialAttack': 140.0,
       'SpecialDefense': 90.0,
       'Speed': 115.0,
       'Total': 600.0,
       'Type': 'DarkFire'},
 249: {'Attack': 95.0,
       'Defense': 95.0,
       'HP': 75.0,
       'Name': 'Kingdra',
       'PokedexNumber': 230.0,
       'SpecialAttack': 95.0,
       'SpecialDefense': 95.0,
       'Speed': 85.0,
       'Total': 540.0,
       'Type': 'WaterDragon'},
 250: {'Attack': 60.0,
       'Defense': 60.0,
       'HP': 90.0,
       'Name': 'Phanpy',
       'PokedexNumber': 231.0,
       'SpecialAttack': 40.0,
       'SpecialDefense': 40.0,
       'Speed': 40.0,
       'Total': 330.0,
       'Type': 'Ground'},
 251: {'Attack': 120.0,
       'Defense': 120.0,
       'HP': 90.0,
       'Name': 'Donphan',
       'PokedexNumber': 232.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 60.0,
       'Speed': 50.0,
       'Total': 500.0,
       'Type': 'Ground'},
 252: {'Attack': 80.0,
       'Defense': 90.0,
       'HP': 85.0,
       'Name': 'Porygon2',


       'Type': 'SteelRock'},
 332: {'Attack': 110.0,
       'Defense': 180.0,
       'HP': 70.0,
       'Name': 'Aggron',
       'PokedexNumber': 306.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 60.0,
       'Speed': 50.0,
       'Total': 530.0,
       'Type': 'SteelRock'},
 333: {'Attack': 140.0,
       'Defense': 230.0,
       'HP': 70.0,
       'Name': 'AggronMega Aggron',
       'PokedexNumber': 306.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 80.0,
       'Speed': 50.0,
       'Total': 630.0,
       'Type': 'Steel'},
 334: {'Attack': 40.0,
       'Defense': 55.0,
       'HP': 30.0,
       'Name': 'Meditite',
       'PokedexNumber': 307.0,
       'SpecialAttack': 40.0,
       'SpecialDefense': 55.0,
       'Speed': 60.0,
       'Total': 280.0,
       'Type': 'FightingPsychic'},
 335: {'Attack': 60.0,
       'Defense': 75.0,
       'HP': 60.0,
       'Name': 'Medicham',
       'PokedexNumber': 308.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 75

       'SpecialDefense': 50.0,
       'Speed': 50.0,
       'Total': 420.0,
       'Type': 'Dragon'},
 408: {'Attack': 135.0,
       'Defense': 80.0,
       'HP': 95.0,
       'Name': 'Salamence',
       'PokedexNumber': 373.0,
       'SpecialAttack': 110.0,
       'SpecialDefense': 80.0,
       'Speed': 100.0,
       'Total': 600.0,
       'Type': 'DragonFlying'},
 409: {'Attack': 145.0,
       'Defense': 130.0,
       'HP': 95.0,
       'Name': 'SalamenceMega Salamence',
       'PokedexNumber': 373.0,
       'SpecialAttack': 120.0,
       'SpecialDefense': 90.0,
       'Speed': 120.0,
       'Total': 700.0,
       'Type': 'DragonFlying'},
 410: {'Attack': 55.0,
       'Defense': 80.0,
       'HP': 40.0,
       'Name': 'Beldum',
       'PokedexNumber': 374.0,
       'SpecialAttack': 35.0,
       'SpecialDefense': 60.0,
       'Speed': 30.0,
       'Total': 300.0,
       'Type': 'SteelPsychic'},
 411: {'Attack': 75.0,
       'Defense': 100.0,
       'HP': 60.0,
       'Name': 'Metang',

       'SpecialAttack': 140.0,
       'SpecialDefense': 70.0,
       'Speed': 112.0,
       'Total': 625.0,
       'Type': 'FightingSteel'},
 499: {'Attack': 72.0,
       'Defense': 78.0,
       'HP': 68.0,
       'Name': 'Hippopotas',
       'PokedexNumber': 449.0,
       'SpecialAttack': 38.0,
       'SpecialDefense': 42.0,
       'Speed': 32.0,
       'Total': 330.0,
       'Type': 'Ground'},
 500: {'Attack': 112.0,
       'Defense': 118.0,
       'HP': 108.0,
       'Name': 'Hippowdon',
       'PokedexNumber': 450.0,
       'SpecialAttack': 68.0,
       'SpecialDefense': 72.0,
       'Speed': 47.0,
       'Total': 525.0,
       'Type': 'Ground'},
 501: {'Attack': 50.0,
       'Defense': 90.0,
       'HP': 40.0,
       'Name': 'Skorupi',
       'PokedexNumber': 451.0,
       'SpecialAttack': 30.0,
       'SpecialDefense': 55.0,
       'Speed': 65.0,
       'Total': 330.0,
       'Type': 'PoisonBug'},
 502: {'Attack': 90.0,
       'Defense': 110.0,
       'HP': 70.0,
       'Name': '

       'Name': 'Excadrill',
       'PokedexNumber': 530.0,
       'SpecialAttack': 50.0,
       'SpecialDefense': 65.0,
       'Speed': 88.0,
       'Total': 508.0,
       'Type': 'GroundSteel'},
 590: {'Attack': 60.0,
       'Defense': 86.0,
       'HP': 103.0,
       'Name': 'Audino',
       'PokedexNumber': 531.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 86.0,
       'Speed': 50.0,
       'Total': 445.0,
       'Type': 'Normal'},
 591: {'Attack': 60.0,
       'Defense': 126.0,
       'HP': 103.0,
       'Name': 'AudinoMega Audino',
       'PokedexNumber': 531.0,
       'SpecialAttack': 80.0,
       'SpecialDefense': 126.0,
       'Speed': 50.0,
       'Total': 545.0,
       'Type': 'NormalFairy'},
 592: {'Attack': 80.0,
       'Defense': 55.0,
       'HP': 75.0,
       'Name': 'Timburr',
       'PokedexNumber': 532.0,
       'SpecialAttack': 25.0,
       'SpecialDefense': 35.0,
       'Speed': 35.0,
       'Total': 305.0,
       'Type': 'Fighting'},
 593: {'Attack': 10

       'HP': 45.0,
       'Name': 'Mienfoo',
       'PokedexNumber': 619.0,
       'SpecialAttack': 55.0,
       'SpecialDefense': 50.0,
       'Speed': 65.0,
       'Total': 350.0,
       'Type': 'Fighting'},
 681: {'Attack': 125.0,
       'Defense': 60.0,
       'HP': 65.0,
       'Name': 'Mienshao',
       'PokedexNumber': 620.0,
       'SpecialAttack': 95.0,
       'SpecialDefense': 60.0,
       'Speed': 105.0,
       'Total': 510.0,
       'Type': 'Fighting'},
 682: {'Attack': 120.0,
       'Defense': 90.0,
       'HP': 77.0,
       'Name': 'Druddigon',
       'PokedexNumber': 621.0,
       'SpecialAttack': 60.0,
       'SpecialDefense': 90.0,
       'Speed': 48.0,
       'Total': 485.0,
       'Type': 'Dragon'},
 683: {'Attack': 74.0,
       'Defense': 50.0,
       'HP': 59.0,
       'Name': 'Golett',
       'PokedexNumber': 622.0,
       'SpecialAttack': 35.0,
       'SpecialDefense': 50.0,
       'Speed': 35.0,
       'Total': 303.0,
       'Type': 'GroundGhost'},
 684: {'Attac

       'Defense': 75.0,
       'HP': 78.0,
       'Name': 'Hawlucha',
       'PokedexNumber': 701.0,
       'SpecialAttack': 74.0,
       'SpecialDefense': 63.0,
       'Speed': 118.0,
       'Total': 500.0,
       'Type': 'FightingFlying'},
 772: {'Attack': 58.0,
       'Defense': 57.0,
       'HP': 67.0,
       'Name': 'Dedenne',
       'PokedexNumber': 702.0,
       'SpecialAttack': 81.0,
       'SpecialDefense': 67.0,
       'Speed': 101.0,
       'Total': 431.0,
       'Type': 'ElectricFairy'},
 773: {'Attack': 50.0,
       'Defense': 150.0,
       'HP': 50.0,
       'Name': 'Carbink',
       'PokedexNumber': 703.0,
       'SpecialAttack': 50.0,
       'SpecialDefense': 150.0,
       'Speed': 50.0,
       'Total': 500.0,
       'Type': 'RockFairy'},
 774: {'Attack': 50.0,
       'Defense': 35.0,
       'HP': 45.0,
       'Name': 'Goomy',
       'PokedexNumber': 704.0,
       'SpecialAttack': 55.0,
       'SpecialDefense': 75.0,
       'Speed': 40.0,
       'Total': 300.0,
       '

In [76]:
# To test the function, print out the pokemon with id = 100.
print(trial[108])

{'PokedexNumber': 100.0, 'Name': 'Voltorb', 'Type': 'Electric', 'Total': 330.0, 'HP': 40.0, 'Attack': 30.0, 'Defense': 50.0, 'SpecialAttack': 55.0, 'SpecialDefense': 55.0, 'Speed': 100.0}


<img src="http://i.imgur.com/GCAf1UX.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 10. Write a function to generate a "filtered" pokedex
---
Your function should:
1. Take the parsed pokedex information you created above as an argument.
1. Take a dictionary as a parameter with keys matching the features of the Pokedex, filtering by exact match for string type values, and/or filter continuous variables specified by a value that is greater than or equal to the value of the corresponding dictionary key parameter.
1. Return multiple elements from the Pokedex

Example:

```python

# Only filter based on parameters passed
filter_options = {
    'Attack':   25,
    'Defense':  30,
    'Type':     'Electric'
}

# Return records with attack >= 25, defense >= 30, and type == "Electric"
# Also anticipate that other paramters can also be passed such as "SpecialAttack", "Speed", etc.
filtered_pokedex(pokedex_data, filter=filter_options)

# Example output:
# [{'Attack': 30.0,
#  'Defense': 50.0,
#  'HP': 40.0,
#  'Name': 'Voltorb',
#  'SpecialAttack': 55.0,
#  'SpecialDefense': 55.0,
#  'Speed': 100.0,
#  'Total': 330.0,
#  'Type': 'Electric'},
#  {'Attack': 30.0,
#  'Defense': 33.0,
#  'HP': 32.0,
#  'Name': 'Pikachu',
#  'SpecialAttack': 55.0,
#  'SpecialDefense': 55.0,
#  'Speed': 100.0,
#  'Total': 330.0,
#  'Type': 'Electric'},
#  ... etc
#  ]

```




## 11. Descriptive statistics on the prototype pokedex

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

### 11.1

What is the population mean and standard deviation of the "Total" attribute for all characters in the Pokedex?



In [80]:
# I imported numpy and pandas to look at the csv file
import pandas as pd
import numpy as np

data = pd.read_csv(pokedex_file)
data

# Using .describe I can see the mean and standard deviation printed for me for each column
data.describe()

PokedexNumber      Total          HP      Attack     Defense  \
count     800.000000  800.00000  800.000000  800.000000  800.000000   
mean      362.813750  435.10250   69.258750   79.001250   73.842500   
std       208.343798  119.96304   25.534669   32.457366   31.183501   
min         1.000000  180.00000    1.000000    5.000000    5.000000   
25%       184.750000  330.00000   50.000000   55.000000   50.000000   
50%       364.500000  450.00000   65.000000   75.000000   70.000000   
75%       539.250000  515.00000   80.000000  100.000000   90.000000   
max       721.000000  780.00000  255.000000  190.000000  230.000000   

       SpecialAttack  SpecialDefense       Speed  
count     800.000000      800.000000  800.000000  
mean       72.820000       71.902500   68.277500  
std        32.722294       27.828916   29.060474  
min        10.000000       20.000000    5.000000  
25%        49.750000       50.000000   45.000000  
50%        65.000000       70.000000   65.000000  
75%        95.000000       90.000000   90.000000  
max       194.000000      230.000000  180.000000

The population mean of 'Total' is 435.10250
The standard deviation of 'Total' is 119.96304

<img src="http://imgur.com/l5NasQj.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

### 11.2

The game is no fun if the characters are wildly unbalanced! Are any characters "overpowered", which we'll define as having a "Total" more than three standard deviations from the population mean?

In [77]:
pop_mean = 435.10250
pop_sd = 119.96304
overpower = pop_mean + (pop_sd * 3)

print('Overpowered would equal more than', overpower)


Overpowered would equal more than 794.99162


In [78]:
# I tried to filter the dataframe to show rows with Total higher than 'overpower' amount
# Nothing was returned, so my answer would be no, no pokemon is overpowered (but I wanted to double check below)
data[(data['Total'] > 794.99162)]

Empty DataFrame
Columns: [PokedexNumber, Name, Type, Total, HP, Attack, Defense, SpecialAttack, SpecialDefense, Speed]
Index: []

In [79]:
# I sorted the data frame on the column 'Total'
# I then used .tail to show the bottom 5 (or biggest 5 totals)
sort = pd.DataFrame(data['Total'].sort_values())
sort.tail()

Total
424    770
422    770
164    780
426    780
163    780

None of these figures are over 794.99162, so there are no pokemon overpowered.

<img src="http://imgur.com/xDpSobf.png" style="float: left; margin: 25px 15px 0px 0px; height: 25px">

## 12. Calibrate the frequency of Pokemon

The design team wants you to make the powerful Pokemon rare, and the weaklings more common. How would you set the probability $p_i$ of finding Pokemon *i* each time a player visits a gym?

Write a function that takes in a Pokedex number and returns a value $p_i$ for that character.

Hint: there are many ways you could do this. What do _you_ think makes sense? Start with simplifying assumptions: for example, you could assume that the probabilities of encountering any two Pokemon on one visit to a gym are independent of each other.

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(data['Total'], bins=20, color='grey')
plt.show()

# This will show the distribution of the pokemon 'Total' values
# i.e. how rare a Total value is

In [ ]:
# I did not get the oppurtunity to complete this, I was researching the below in order to make some sort of headway

# pdf_probability = scipy.stats.norm.pdf(x, loc=0, scale=1)
# pdf(x, loc=0, scale=1)
# Probability density function.
# logpdf(x, loc=0, scale=1)

#P(E|F) = P(E)
